Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "whamoumiS" do |control|
    control.vm.hostname = "whamoumiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.synced_folder "./confs", "/home/vagrant/data", type: 'nfs', nfs_version: 4, nfs_udp: false
    control.vm.network "forwarded_port", guest: 80, host:8080
    control.vm.provider "libvirt" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install ufw -y
      sudo ufw enable
      sudo ufw allow 6443/tcp
      sudo apt-get install -y nfs-common

      curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644
      
      # Ordre recommandé :
      # 1. ConfigMaps
      kubectl apply -f /home/vagrant/data/config/app1.yaml
      kubectl apply -f /home/vagrant/data/config/app2.yaml
      kubectl apply -f /home/vagrant/data/config/app3.yaml
      
      # 2. Deployments
      kubectl apply -f /home/vagrant/data/deployment/deployment1.yaml
      kubectl apply -f /home/vagrant/data/deployment/deployment2.yaml
      kubectl apply -f /home/vagrant/data/deployment/deployment3.yaml
      
      # 3. Services
      kubectl apply -f /home/vagrant/data/service/service1.yaml
      kubectl apply -f /home/vagrant/data/service/service2.yaml
      kubectl apply -f /home/vagrant/data/service/service3.yaml
      
      # 4. Ingress
      kubectl apply -f /home/vagrant/data/ingress/ingress.yaml

    SHELL
  end
end
