Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "whamoumiS" do |control|
    control.vm.hostname = "whamoumiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.synced_folder "./data", "/home/vagrant/data", type: 'nfs', nfs_version: 4, nfs_udp: false
    control.vm.provider "libvirt" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install ufw -y
      sudo ufw enable
      sudo ufw allow 6443/tcp
      sudo apt-get install -y nfs-common

      curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode 644
      sudo cat /var/lib/rancher/k3s/server/node-token > /home/vagrant/data/secret.txt
      sudo chown vagrant:vagrant /home/vagrant/data/secret.txt
    SHELL
  end

  config.vm.define "whamoumiSW" do |control|
    control.vm.hostname = "whamoumiSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.synced_folder "./data", "/home/vagrant/data", type: 'nfs', nfs_version: 4, nfs_udp: false
    control.vm.provider "libvirt" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nfs-common
      sudo apt-get install -y iptables
      while [ ! -f /home/vagrant/data/secret.txt ]; do
        sleep 2
      done
      # Attendre que le token soit disponible
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /home/vagrant/data/secret.txt) sh -s - agent
    SHELL
  end
end
